[env:esp32-s3-n8r8]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
upload_protocol = esp-builtin
build_flags = 
    -DBOARD_HAS_PSRAM
    -DARDUINO_USB_MODE=1
    -DARDUINO_USB_CDC_ON_BOOT=1
board_build.arduino.memory_type = qio_opi
board_build.flash_mode = qio
board_upload.flash_size = 8MB
board_upload.maximum_size = 8388608
board_build.partitions = default_8MB.csv
lib_deps =
    adafruit/Adafruit BNO08x
    adafruit/Adafruit Unified Sensor
    adafruit/Adafruit BusIO
    SPI